version: '3.8'

services:
  # MySQL数据库（低内存优化）
  mysql:
    image: mysql:8.0
    container_name: ipv6wgm-mysql-low
    environment:
      MYSQL_DATABASE: ipv6wgm
      MYSQL_USER: ipv6wgm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/low-memory.cnf:/etc/mysql/conf.d/low-memory.cnf
    ports:
      - "3306:3306"
    networks:
      - ipv6wgm-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=64M --max-connections=50

  # 后端API服务（低内存优化）
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ipv6wgm-backend-low
    environment:
      - DATABASE_URL=mysql://ipv6wgm:password@mysql:3306/ipv6wgm
      - SECRET_KEY=your-secret-key-here
      - DEBUG=false
      - DATABASE_POOL_SIZE=5
      - DATABASE_MAX_OVERFLOW=10
      - MAX_WORKERS=2
    volumes:
      - ./backend:/app
      - /etc/wireguard:/etc/wireguard:ro
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - ipv6wgm-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # 前端服务 (包含Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ipv6wgm-frontend-low
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_WS_URL=ws://backend:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ipv6wgm-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  mysql_data:

networks:
  ipv6wgm-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        - subnet: 2001:db8::/64
